# -*- coding: utf-8 -*-
"""기말 프로젝트_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Plez560udxY5uzzEm0hQ41Th3XSgxb4R
"""

!apt-get update
!apt-get install -y fonts-nanum

import matplotlib.pyplot as plt
import matplotlib.font_manager as fm
import matplotlib as mpl

# 설치된 나눔폰트 로드
font_path = "/usr/share/fonts/truetype/nanum/NanumGothic.ttf"
fm.fontManager.addfont(font_path)

plt.rc('font', family='NanumGothic')
mpl.rcParams['axes.unicode_minus'] = False

print("✅ 한국어 폰트 적용 완료!")

import pandas as pd
import matplotlib.pyplot as plt

start = "2019-01-01"
end   = "2025-01-01"

# --- Stooq에서 데이터 다운로드 ---
krw_url = "https://stooq.com/q/d/l/?s=usdkrw&i=d"
kospi_url = "https://stooq.com/q/d/l/?s=^kospi&i=d"

krw = pd.read_csv(krw_url, parse_dates=["Date"])
kospi = pd.read_csv(kospi_url, parse_dates=["Date"])

# 날짜 필터링
krw = krw[krw["Date"] >= start].set_index("Date")
kospi = kospi[kospi["Date"] >= start].set_index("Date")

# Align index
df = pd.concat([
    krw["Close"],
    kospi["Close"]
], axis=1, keys=["USDKRW", "KOSPI"]).dropna()

# 변동률 계산
df_returns = df.pct_change().dropna()

print("상관계수:")
print(df_returns.corr())

# 시각화
df_norm = df / df.iloc[0] * 100
plt.figure(figsize=(10,5))
plt.title("달러 환율과 한국 주식(KOSPI) 추세 비교 그래프")
plt.plot(df_norm.index, df_norm["USDKRW"], label="USD/KRW 정규화")
plt.plot(df_norm.index, df_norm["KOSPI"], label="KOSPI 정규화")
plt.legend()
plt.grid(True)
plt.show()