# -*- coding: utf-8 -*-
"""기말 프로젝트_6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zzVEoZF_K08ouEX8dZrhqPpWQGgosop-
"""

!pip install prophet
!pip install tensorflow
!apt-get update -qq
!apt-get install -y fonts-nanum
!fc-cache -fv

import matplotlib.pyplot as plt
import matplotlib.font_manager as fm
import matplotlib as mpl

# 나눔고딕 폰트 등록
font_dirs = ['/usr/share/fonts/truetype/nanum']
font_files = fm.findSystemFonts(fontpaths=font_dirs)

for f in font_files:
    fm.fontManager.addfont(f)

plt.rc('font', family='NanumGothic')
mpl.rcParams['axes.unicode_minus'] = False  # 마이너스 깨짐 방지

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import yfinance as yf

from statsmodels.tsa.arima.model import ARIMA
from prophet import Prophet
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense


# =====================
# 1. 데이터 다운로드
# =====================
data = yf.download("^KS11", start="2000-01-01", end="2025-01-01", auto_adjust=True)
close = data['Close']

# 학습 (2000~2010), 예측 대상 (2011~2025)
train = close[:'2010-12-31']
test = close['2011-01-01':]


# =====================
# 2. ARIMA 모델
# =====================
arima_model = ARIMA(train, order=(5,1,0)).fit()
arima_pred = arima_model.forecast(steps=len(test))
arima_pred.index = test.index


# =====================
# 3. LSTM 모델 (빠른 버전)
# =====================

scaler = MinMaxScaler()
scaled_full = scaler.fit_transform(close.values.reshape(-1,1))

seq_len = 60

def create_dataset(series, seq_len=60):
    X, y = [], []
    for i in range(seq_len, len(series)):
        X.append(series[i-seq_len:i])
        y.append(series[i])
    return np.array(X), np.array(y)

X_all, y_all = create_dataset(scaled_full, seq_len)

# X_all과 close의 인덱스를 맞추기
full_index = close.index[seq_len:]

# train/test 비율 맞추기
split_idx = full_index.get_loc(test.index[0])

X_train = X_all[:split_idx]
y_train = y_all[:split_idx]

X_test = X_all[split_idx:]
y_test_scaled = y_all[split_idx:]


# LSTM 모델 구성
model_lstm = Sequential([
    LSTM(64, return_sequences=True, input_shape=(seq_len, 1)),
    LSTM(32),
    Dense(1)
])
model_lstm.compile(loss="mse", optimizer="adam")

model_lstm.fit(X_train, y_train, epochs=10, batch_size=32, verbose=0)

# test 전체를 한 번에 예측
lstm_pred_scaled = model_lstm.predict(X_test)
lstm_pred = scaler.inverse_transform(lstm_pred_scaled).flatten()
lstm_pred = pd.Series(lstm_pred, index=test.index)


# =====================
# 4. Prophet 모델
# =====================
df_p = train.reset_index()
df_p.columns = ['ds','y']

model_p = Prophet()
model_p.fit(df_p)

future = pd.DataFrame({"ds": test.index})
forecast = model_p.predict(future)

prophet_pred = forecast.set_index("ds")["yhat"]


# =====================
# 5. 그래프 출력 (3개 가로 배치)
# =====================
plt.figure(figsize=(22,6))
plt.suptitle("KOSPI 예측 비교 (ARIMA / LSTM / Prophet)", fontsize=17)

# ARIMA
ax1 = plt.subplot(1,3,1)
ax1.plot(test.index, test, label="실제값")
ax1.plot(arima_pred.index, arima_pred, label="ARIMA 예측")
ax1.set_title("1) ARIMA")
ax1.legend()

# LSTM
ax2 = plt.subplot(1,3,2)
ax2.plot(test.index, test, label="실제값")
ax2.plot(lstm_pred.index, lstm_pred, label="LSTM 예측")
ax2.set_title("2) LSTM")
ax2.legend()

# Prophet
ax3 = plt.subplot(1,3,3)
ax3.plot(test.index, test, label="실제값")
ax3.plot(prophet_pred.index, prophet_pred, label="Prophet 예측")
ax3.set_title("3) Prophet")
ax3.legend()

plt.tight_layout()
plt.show()

# =====================
# 6. LSTM 기반 미래 예측
# =====================

future_days = 1095  # 예측하고 싶은 미래 일수 (예: 1년)
last_input = scaled_full[-seq_len:]  # 마지막 60개 데이터
future_preds = []

for _ in range(future_days):
    pred_scaled = model_lstm.predict(last_input.reshape(1, seq_len, 1), verbose=0)
    future_preds.append(pred_scaled[0][0])

    # 입력 슬라이딩
    last_input = np.append(last_input[1:], pred_scaled).reshape(seq_len, 1)

# 스케일 역변환
future_preds = scaler.inverse_transform(np.array(future_preds).reshape(-1,1)).flatten()

# 미래 날짜 생성
last_date = close.index[-1]
future_index = pd.date_range(start=last_date + pd.Timedelta(days=1), periods=future_days)

future_series = pd.Series(future_preds, index=future_index)

plt.figure(figsize=(16,6))
plt.title("LSTM 기반 KOSPI 예측 (실제 · 테스트예측 · 미래예측)")

# 실제 데이터
plt.plot(close.index, close, label="실제값")

# test 구간 예측
plt.plot(lstm_pred.index, lstm_pred, label="LSTM 예측 (2011~2025)")

# 미래 예측
plt.plot(future_series.index, future_series, label="LSTM 미래 예측 (2025~)", linestyle="--")

plt.xlabel("날짜")
plt.ylabel("KOSPI 지수")
plt.legend()
plt.grid(True)
plt.show()