"""기말프로젝트_2.ipynb
Step_2. 한국장 vs. 미국장 주가 비교 그래프

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YhXd6FRvx-c8gVZMSfYy2lb2jhEEo627
"""

# 1. 한글 폰트 설치 (Colab 전용)
# !apt-get update -qq
# !apt-get install -y fonts-nanum

# 2. 한글 폰트 적용
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm
import matplotlib as mpl
import pandas as pd

font_dirs = ['/usr/share/fonts/truetype/nanum']
font_files = fm.findSystemFonts(fontpaths=font_dirs)

for fpath in font_files:
    fm.fontManager.addfont(fpath)

plt.rc('font', family='NanumGothic')
mpl.rcParams['axes.unicode_minus'] = False

## KOSPI, S&P 500 데이터를 무료 제공하는 stooq 사이트의 데이터 이용 (일월주 단위, csv형식 제공)
kospi_url = "https://stooq.com/q/d/l/?s=^kospi&i=m"
spx_url   = "https://stooq.com/q/d/l/?s=^spx&i=m"

kospi_df = pd.read_csv(kospi_url, parse_dates=['Date'])
spx_df   = pd.read_csv(spx_url,   parse_dates=['Date'])

## 기간 필터링 (2019년 이후)
start_date = "2019-01-01"
kospi_recent = kospi_df[kospi_df['Date'] >= start_date].copy()
spx_recent   = spx_df[spx_df['Date'] >= start_date].copy()

print(kospi_recent)

## 정규화(첫 달 = 100)를 통해 변동성에 집중
kospi_recent['Normalized'] = kospi_recent['Close'] / kospi_recent['Close'].iloc[0] * 100
spx_recent['Normalized']   = spx_recent['Close']   / spx_recent['Close'].iloc[0]   * 100

## 수익률(변동률) 계산
kospi_recent['Return'] = kospi_recent['Close'].pct_change()
spx_recent['Return']   = spx_recent['Close'].pct_change()

## 선 그래프
plt.figure(figsize=(10, 5))
plt.plot(kospi_recent['Date'], kospi_recent['Normalized'], label="KOSPI (정규화)")
plt.plot(spx_recent['Date'],   spx_recent['Normalized'],   label="S&P 500 (정규화)")

plt.title("KOSPI vs S&P 500 월별 추세 (정규화)")
plt.xlabel("날짜")
plt.ylabel("지수 (첫 달 = 100)")
plt.legend()
plt.grid(True)
plt.show()

# 2. 상관계수 예측 (corr)
kospi_recent['YearMonth'] = kospi_recent['Date'].dt.to_period('M')
spx_recent['YearMonth']   = spx_recent['Date'].dt.to_period('M')

## 월별 수익률 계산
kospi_return = kospi_recent.groupby('YearMonth')['Close'].last().pct_change()
spx_return   = spx_recent.groupby('YearMonth')['Close'].last().pct_change()

## 데이터 합치기
ret_df = pd.concat([kospi_return, spx_return], axis=1)
ret_df.columns = ['KOSPI_Return', 'SP500_Return']

## 결측치 제거
ret_df = ret_df.dropna()

## 상관계수 계산
corr_value = ret_df['KOSPI_Return'].corr(ret_df['SP500_Return'])

print("KOSPI ↔ S&P500 상관계수:", corr_value)