# -*- coding: utf-8 -*-
"""기말 프로젝트_8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O0KeI715k5J6pchBlSbdKnnJQH_1j65X
"""

!apt-get update -qq
!apt-get install -y fonts-nanum
!fc-cache -fv

import matplotlib.pyplot as plt
import matplotlib.font_manager as fm
import matplotlib as mpl

# 나눔폰트 로드
font_path = "/usr/share/fonts/truetype/nanum/NanumGothic.ttf"
fm.fontManager.addfont(font_path)

plt.rc('font', family='NanumGothic')
mpl.rcParams['axes.unicode_minus'] = False

import pandas as pd

# ====== 1. KOSPI / SPX 데이터 다운로드 ======
kospi_url = "https://stooq.com/q/d/l/?s=^kospi&i=m"
spx_url   = "https://stooq.com/q/d/l/?s=^spx&i=m"

kospi_df = pd.read_csv(kospi_url, parse_dates=['Date'])
spx_df   = pd.read_csv(spx_url,   parse_dates=['Date'])

# ====== 2. 기간 필터링 ======
start_date = "2019-01-01"
kospi_recent = kospi_df[kospi_df['Date'] >= start_date].copy()
spx_recent   = spx_df[spx_df['Date'] >= start_date].copy()

# ====== 3. 수익률 계산 ======
kospi_recent["KOSPI_Return"] = kospi_recent["Close"].pct_change()
spx_recent["SPX_Return"] = spx_recent["Close"].pct_change()

# ====== 4. 날짜 기준 merge ======
data = pd.merge(
    kospi_recent[["Date", "KOSPI_Return"]],
    spx_recent[["Date", "SPX_Return"]],
    on="Date",
    how="inner"
).dropna()

data.set_index("Date", inplace=True)

print("data 확인")
print(data.head())
print(data.tail())
print("data 개수:", len(data))

# ====== 5. train / test 분리 ======
train = data[:'2023-12-31']
test  = data['2024-01-01':]

print("\nTrain:", train.index[0], "~", train.index[-1])
print("Test:", test.index[0], "~", test.index[-1])

# 모델1. 선형 회귀

from sklearn.linear_model import LinearRegression

X_train = train[['SPX_Return']]
y_train = train['KOSPI_Return']

X_test  = test[['SPX_Return']]
y_test  = test['KOSPI_Return']

lr_model = LinearRegression().fit(X_train, y_train)
lr_pred  = lr_model.predict(X_test)

print("선형회귀 계수:", lr_model.coef_, "절편:", lr_model.intercept_)

# 모델2. VAR (Vector Auttoregression)

# from statsmodels.tsa.api import VAR

# var_train = train.copy()
# model_var = VAR(var_train)
# var_result = model_var.fit(maxlags=3)

# var_pred = var_result.forecast(var_train.values[-3:], steps=len(test))
# var_pred_df = pd.DataFrame(var_pred, index=test.index, columns=['SPX_pred','KOSPI_pred'])

from statsmodels.tsa.vector_ar.var_model import VAR

# VAR 모델 학습
var_model = VAR(train)
var_result = var_model.fit(maxlags=4)  # 적절히 수정 가능 (AIC 기반 선택 가능)

# 예측 수행
var_forecast = var_result.forecast(train.values, steps=len(test))

# 예측값 배열 → DataFrame 변환
var_pred_df = pd.DataFrame(var_forecast, index=test.index, columns=train.columns)

# 우리는 KOSPI만 사용
var_kospi_pred = var_pred_df["KOSPI_Return"]

# 모델3. LSTM (SPX로 KOSPI 예측)

from sklearn.preprocessing import MinMaxScaler
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

# 1) 스케일링
scaler = MinMaxScaler()
scaled = scaler.fit_transform(data)

scaled_df = pd.DataFrame(scaled, index=data.index, columns=data.columns)

# 2) 시퀀스 생성 함수
def create_seq(dataset, window=12):
    X, y = [], []
    for i in range(window, len(dataset)):
        X.append(dataset[i-window:i, 0])  # SPX_Return 입력
        y.append(dataset[i, 1])           # KOSPI_Return 출력
    return np.array(X), np.array(y)

window = 12
X, y = create_seq(scaled_df.values, window)

split = len(train)
X_train, X_test = X[:split-window], X[split-window:]
y_train, y_test_lstm = y[:split-window], y[split-window:]

# reshape for LSTM
X_train = X_train.reshape(-1, window, 1)
X_test  = X_test.reshape(-1, window, 1)

# 3) LSTM 모델 구성
lstm_model = Sequential([
    LSTM(64, return_sequences=True, input_shape=(window,1)),
    LSTM(32),
    Dense(1)
])

lstm_model.compile(optimizer='adam', loss='mse')
lstm_model.fit(X_train, y_train, epochs=30, batch_size=8, verbose=1)

# 4) 예측
lstm_pred = lstm_model.predict(X_test)

# 역스케일링용

import numpy as np

# target 컬럼 인덱스 (KOSPI_Return)
target_idx = scaled_df.columns.get_loc("KOSPI_Return")  # 보통 1일 것

# 예측값 역스케일링용 dummy 배열
dummy_pred = np.zeros((len(lstm_pred), scaled_df.shape[1]))
dummy_pred[:, target_idx] = lstm_pred.reshape(-1)

inv_all = scaler.inverse_transform(dummy_pred)
lstm_pred_inv = inv_all[:, target_idx]  # KOSPI_Return만 추출

# 모델별 예측 정확도 비교

def evaluate(y_true, y_pred, name=""):
    mse = mean_squared_error(y_true, y_pred)
    mae = mean_absolute_error(y_true, y_pred)
    rmse = np.sqrt(mse)
    print(f"\n📌 {name} 모델 정확도")
    print("MAE :", mae)
    print("MSE :", mse)
    print("RMSE:", rmse)

evaluate(test["KOSPI_Return"], lr_pred, "선형회귀")
evaluate(test["KOSPI_Return"], var_kospi_pred, "VAR")
evaluate(test["KOSPI_Return"], lstm_pred_inv[:len(test)], "LSTM")

# 그래프 비교 출력

plt.figure(figsize=(12,6))
plt.plot(test.index, test["KOSPI_Return"], label="실제 KOSPI", linewidth=2)
plt.plot(test.index, lr_pred, label="Linear Regression 예측")
plt.plot(test.index, var_kospi_pred, label="VAR 예측")
plt.plot(test.index, lstm_pred_inv[:len(test)], label="LSTM 예측")
plt.title("미국장(S&P500) 기반 한국장(KOSPI) 예측 비교")
plt.xlabel("날짜")
plt.ylabel("KOSPI Return")
plt.legend()
plt.grid(True)
plt.show()