# -*- coding: utf-8 -*-
"""기말 프로젝트_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZH8BVnB8Gb1dvI72anYZl4835KM5emPg
"""

!apt-get update
!apt-get install -y fonts-nanum
!fc-cache -fv

# 1. 나눔고딕 직접 다운로드
!wget -O NanumGothic.ttf "https://github.com/google/fonts/raw/main/ofl/nanumgothic/NanumGothic-Regular.ttf"

# 2. Matplotlib에 직접 등록
import matplotlib.font_manager as fm
import matplotlib.pyplot as plt

fm.fontManager.addfont("NanumGothic.ttf")
plt.rcParams['font.family'] = 'NanumGothic'
plt.rcParams['axes.unicode_minus'] = False

# 3. 테스트
# plt.figure(figsize=(6,4))
# plt.title("한글 나오냐 테스트")
# plt.plot([1,2,3], [1,4,9])
# plt.xlabel("가로축")
# plt.ylabel("세로축")
# plt.show()

import pandas as pd
import yfinance as yf

# 데이터 다운로드 (예시)
data = {
    "Gold": yf.download("GLD", start="2019-01-01", end="2025-01-01")["Close"],
    "Bitcoin": yf.download("BTC-USD", start="2019-01-01", end="2025-01-01")["Close"],
    "KOSPI": yf.download("^KS11", start="2019-01-01", end="2025-01-01")["Close"],
}

df = pd.concat(data.values(), axis=1, keys=data.keys()).dropna()
df_returns = df.pct_change().dropna()
print(df_returns.corr())  # 상관계수 행렬 출력

import seaborn as sns

sns.heatmap(df_returns.corr(), annot=True, cmap='coolwarm')
plt.title("금, 코인, 주식(KOSPI) 상관계수 Heatmap")
plt.show()

# 4. 세 시장 데이터를 한 그래프에서 비교 (정규화)

df_norm = df / df.iloc[0] * 100   # 첫날 = 100으로 정규화

plt.figure(figsize=(12, 6))
plt.plot(df_norm.index, df_norm["Gold"], label="Gold (정규화)")
plt.plot(df_norm.index, df_norm["Bitcoin"], label="Bitcoin (정규화)")
plt.plot(df_norm.index, df_norm["KOSPI"], label="KOSPI (정규화)")

plt.title("금 · 비트코인 · KOSPI 시장 비교 (정규화)")
plt.xlabel("날짜")
plt.ylabel("지수 (첫날 = 100)")
plt.legend()
plt.grid(True)
plt.show()