# -*- coding: utf-8 -*-
"""기말 프로젝트_5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K1b-rgABlki5qjsfL7q_QhIQxFwoSOVq
"""

# 라이브러리 설치 (최초 1회만 실행)
!pip install finance-datareader
!apt-get update -qq
!apt-get install -y fonts-nanum

import pandas as pd
import matplotlib.pyplot as plt
import FinanceDataReader as fdr
import matplotlib.font_manager as fm
import matplotlib as mpl

# --- 설치된 나눔 폰트 적용 ---
font_dirs = ['/usr/share/fonts/truetype/nanum']
font_files = fm.findSystemFonts(fontpaths=font_dirs)

for fpath in font_files:
    fm.fontManager.addfont(fpath)

plt.rc('font', family='NanumGothic')
mpl.rcParams['axes.unicode_minus'] = False

# 주식 비교를 위한 파이썬 라이브러리 사용

# 비교할 기간 설정
start_date = "2019-01-01"
end_date   = "2025-01-01"

# KOSPI, KOSDAQ 지수 데이터를 FinanceDataReader에서 불러오기
# 지수명은 'KOSPI'와 'KOSDAQ'으로 지정
kospi_df  = fdr.DataReader('KOSPI',  start_date, end_date).reset_index()
kosdaq_df = fdr.DataReader('KOSDAQ', start_date, end_date).reset_index()

# 날짜 컬럼 이름을 맞춰주기 (FinanceDataReader는 'Date' 대신 'index'를 반환함)
kospi_df.rename(columns={'index':'Date'}, inplace=True)
kosdaq_df.rename(columns={'index':'Date'}, inplace=True)

# 정규화(첫 달 = 100)
kospi_df['Norm']  = kospi_df['Close'] / kospi_df['Close'].iloc[0] * 100
kosdaq_df['Norm'] = kosdaq_df['Close'] / kosdaq_df['Close'].iloc[0] * 100

# 그래프 그리기
plt.figure(figsize=(10,5))
plt.plot(kospi_df['Date'],  kospi_df['Norm'],  label="KOSPI (정규화)")
plt.plot(kosdaq_df['Date'], kosdaq_df['Norm'], label="KOSDAQ (정규화)")
plt.title("KOSPI vs KOSDAQ 정규화 추세 (2019~)")
plt.xlabel("날짜")
plt.ylabel("지수 (첫 달 = 100)")
plt.legend()
plt.grid(True)
plt.show()

# --- 월 단위로 변환 ---
kospi_df['YearMonth'] = kospi_df['Date'].dt.to_period('M')
kosdaq_df['YearMonth']   = kosdaq_df['Date'].dt.to_period('M')

# 월별 수익률 계산
kospi_return = kospi_df.groupby('YearMonth')['Close'].last().pct_change()
kosdaq_return   = kosdaq_df.groupby('YearMonth')['Close'].last().pct_change()

# 데이터 합치기
ret_df = pd.concat([kospi_return, kosdaq_return], axis=1)
ret_df.columns = ['KOSPI_Return', 'KOSDAQ_Return']

# 결측치 제거
ret_df = ret_df.dropna()

# 상관계수 계산
corr_value = ret_df['KOSPI_Return'].corr(ret_df['KOSDAQ_Return'])

print("KOSPI ↔ KOSDAQ 상관계수:", corr_value)

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

# ------------------------------------------------------
# 1) 시퀀스 데이터 생성 함수
# ------------------------------------------------------
def create_sequences(data, window=60):
    X, y = [], []
    for i in range(window, len(data)):
        X.append(data[i - window:i])
        y.append(data[i])
    return np.array(X), np.array(y)

# ------------------------------------------------------
# 2) LSTM 예측 수행 함수
# ------------------------------------------------------
def run_lstm_prediction(df, label="KOSPI"):
    print(f"\n===== {label} LSTM 예측 시작 =====")

    # 1. Close 데이터만 사용
    close = df["Close"].values.reshape(-1, 1)

    # 2. Scaling
    scaler = MinMaxScaler()
    scaled = scaler.fit_transform(close)

    # 3. Sequence 생성
    window = 60
    X_all, y_all = create_sequences(scaled, window)

    # 4. Train/Test 분리 (80/20)
    split = int(len(X_all) * 0.8)
    X_train, X_test = X_all[:split], X_all[split:]
    y_train, y_test = y_all[:split], y_all[split:]

    # 5. LSTM 모델 구성
    model = Sequential([
        LSTM(64, return_sequences=True, input_shape=(window, 1)),
        LSTM(32),
        Dense(1)
    ])

    model.compile(optimizer="adam", loss="mse")
    model.fit(X_train, y_train, epochs=15, batch_size=32, validation_split=0.1, verbose=1)

    # 6. 예측
    y_pred = model.predict(X_test)

    # 7. 역스케일링
    y_pred_inv = scaler.inverse_transform(y_pred)
    y_test_inv = scaler.inverse_transform(y_test)

    # 8. 예측 결과 그래프 출력
    plt.figure(figsize=(12,5))
    plt.plot(df["Date"].iloc[-len(y_test_inv):], y_test_inv, label=f"{label} 실제")
    plt.plot(df["Date"].iloc[-len(y_pred_inv):], y_pred_inv, label=f"{label} 예측", linestyle="--")
    plt.title(f"{label} LSTM 기반 예측")
    plt.xlabel("날짜")
    plt.ylabel("지수")
    plt.legend()
    plt.grid(True)
    plt.show()

    return model, y_pred_inv, y_test_inv

# ------------------------------------------------------
# 3) KOSPI & KOSDAQ LSTM 예측 실행
# ------------------------------------------------------

kospi_model, kospi_pred, kospi_true = run_lstm_prediction(kospi_df, label="KOSPI")
kosdaq_model, kosdaq_pred, kosdaq_true = run_lstm_prediction(kosdaq_df, label="KOSDAQ")