"""기말프로젝트1.ipynb
Step_1. 분야별 주식 종목 평균주가 및 평균 등락율 시각화

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TxJfriaxaTuygA9o4yHzZPIgwyNvpCsZ
"""
# -- 1. 패키지 설치 --
# !apt-get update
# !apt install -y chromium-chromedriver
# !pip install selenium pandas matplotlib bs4
# !apt-get install -y fonts-nanum
# !pip install webdriver-manager
# !apt-get update
# !apt-get install -y wget unzip
## Chrome 설치
# !wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
# !apt-get -y install ./google-chrome-stable_current_amd64.deb
## ChromeDriver 설치 (Chrome 버전에 맞춰 자동 다운로드)
# !CHROME_VERSION=$(google-chrome --version | sed 's/Google Chrome //')
# !wget -O chromedriver.zip https://storage.googleapis.com/chrome-for-testing-public/${CHROME_VERSION}/linux64/chromedriver-linux64.zip
# !unzip chromedriver.zip
# !mv chromedriver-linux64/chromedriver /usr/bin/chromedriver
# !chmod +x /usr/bin/chromedriver
# !pip install squarify

# -- 2. 한국어글꼴 적용 --
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm
import matplotlib as mpl
import os

font_dirs = ['/usr/share/fonts/truetype/nanum']
font_files = fm.findSystemFonts(fontpaths=font_dirs)

for fpath in font_files:
    fm.fontManager.addfont(fpath)

fm._load_fontmanager(try_read_cache=False)

plt.rc('font', family='NanumGothic')
mpl.rcParams['axes.unicode_minus'] = False

print([f.name for f in fm.fontManager.ttflist if 'Nanum' in f.name])

# -- 3. 한경 주식 데이터 페이지 크롤링 --
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager # Import ChromeDriverManager
from bs4 import BeautifulSoup
import pandas as pd
import time

chrome_options = Options()
chrome_options.add_argument("--headless")
chrome_options.add_argument("--no-sandbox")
chrome_options.add_argument("--disable-dev-shm-usage")
chrome_options.add_argument("--disable-gpu")
chrome_options.add_argument("--window-size=1920,1080")
chrome_options.binary_location = '/usr/bin/google-chrome-stable'

service = Service(ChromeDriverManager().install())
driver = webdriver.Chrome(service=service, options=chrome_options)
driver.get("https://datacenter.hankyung.com/equities-all")

html = driver.page_source
driver.quit()

soup = BeautifulSoup(html, "lxml")

groups = soup.select("div.equities-group")
data = []

for group in groups:
    category = group.select_one(".group-tit .ellip").get_text(strip=True)
    for li in group.select("li"):
        name_tag = li.select_one(".stock-title a")
        price_tag = li.select_one(".price")
        rate_tag = li.select_one(".rate")
        if name_tag and price_tag and rate_tag:
            name = name_tag.get_text(strip=True)
            price = price_tag.get_text(strip=True).replace(",", "")
            rate = rate_tag.get_text(strip=True).replace("%", "").replace("+", "")
            price = pd.to_numeric(price, errors="coerce")
            rate = pd.to_numeric(rate, errors="coerce")
            data.append({"분야": category, "종목": name, "현재가": price, "등락률": rate})

df = pd.DataFrame(data)
print(df.head())
print(f"총 {len(df)}개 종목 수집 완료")
print("--------------------------")
print(df['분야'].value_counts())

## 크롤링 데이터 csv파일로 다운로드하여 내역 확인 가능
df.to_csv('hankyung_stocks.csv', index=False, encoding='utf-8-sig')

# -- 4. 막대 차트 그래프 --
if not df.empty and "현재가" in df.columns:
  df = df.dropna(subset=["현재가", "등락률"])
  grouped = df.groupby("분야")[["현재가", "등락률"]].mean().reset_index()

  ## HTMl 파일로 저장
  df.to_html("전체_종목_데이터.html", index=False, escape=False)
  grouped.to_html("분야별_평균_데이터.html", index=False, escape=False)
  print("📁 HTML 저장 완료: 전체_종목_데이터.html / 분야별_평균_데이터.html")


  ## 평균 주가 그래프
  plt.figure(figsize=(12,6))
  plt.bar(grouped["분야"], grouped["현재가"], color="skyblue")
  plt.xticks(rotation=90)
  plt.title("분야별 평균 주가")
  plt.xlabel("분야")
  plt.ylabel("평균 현재가")
  plt.tight_layout()
  plt.show()

  ## 평균 등락률 그래프
  plt.figure(figsize=(12,6))
  plt.bar(grouped["분야"], grouped["등락률"], color="orange")
  plt.xticks(rotation=90)
  plt.title("분야별 평균 등락률(%)")
  plt.xlabel("분야")
  plt.ylabel("평균 등락률(%)")
  plt.tight_layout()
  plt.show()
else:
  print("❌ 데이터가 비어 있습니다. HTML 구조 변경 또는 로드 실패.")

# -- 5. 레이더 차트  --
import numpy as np

labels = grouped["분야"].tolist()
num_vars = len(labels)

angles = np.linspace(0, 2 * np.pi, num_vars, endpoint=False).tolist()
angles += angles[:1]

values_price = grouped["현재가"].tolist()
values_price += values_price[:1]
values_return = grouped["등락률"].tolist()
values_return += values_return[:1]

fig, axes = plt.subplots(1, 2, figsize=(14, 6), subplot_kw={"projection": "polar"})

## 평균 주가
axes[0].plot(angles, values_price, linewidth=2)
axes[0].fill(angles, values_price, alpha=0.25)
axes[0].set_title("분야별 평균 주가 레이더 차트", pad=25)   # ← 간격 넓힘
axes[0].set_xticks(angles[:-1])
axes[0].set_xticklabels(labels, fontsize=7)

## 평균 등락률
axes[1].plot(angles, values_return, color="orange", linewidth=2)
axes[1].fill(angles, values_return, alpha=0.25, color="orange")
axes[1].set_title("분야별 평균 등락률 레이더 차트", pad=25)  # ← 간격 넓힘
axes[1].set_xticks(angles[:-1])
axes[1].set_xticklabels(labels, fontsize=7)

plt.tight_layout()
plt.subplots_adjust(top=0.85)  # ← 전체 여백 추가
plt.show()

# 6. 트리맵 (평균 주가 / 평균 등락률)
import squarify
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

fig, axes = plt.subplots(1, 2, figsize=(16, 7))

## 평균 주가
squarify.plot(
    sizes=grouped["현재가"],
    label=grouped["분야"],
    color=sns.color_palette("Blues", len(grouped)),
    ax=axes[0],
    alpha=0.8
)
axes[0].set_title("분야별 평균 주가 Treemap", pad=15)
axes[0].axis('off')

## 평균 등락률
squarify.plot(
    sizes=np.abs(grouped["등락률"]),   # 절대값 사용
    label=grouped["분야"],
    color=sns.color_palette("Oranges", len(grouped)),
    ax=axes[1],
    alpha=0.8
)
axes[1].set_title("분야별 평균 등락률 Treemap", pad=15)
axes[1].axis('off')

plt.tight_layout()
plt.show()

##  7. 버블 차트
import numpy as np
import matplotlib.pyplot as plt

fig, axes = plt.subplots(1, 2, figsize=(16, 7))


## 투명도(알파) 스케일링 함수
def normalize_alpha(values):
    v = (values - values.min()) / (values.max() - values.min() + 1e-6)
    return 0.1 + v * 0.9    # ★ 범위 0.1 ~ 1.0 (진하기 차이 강조)


## 평균 주가 기반 버블 차트
bubble_size_price = grouped["현재가"] / 10

alpha_price = normalize_alpha(grouped["현재가"])   # 진하기 = 평균 주가 기준

axes[0].scatter(
    grouped["등락률"],
    grouped["현재가"],
    s=bubble_size_price,
    alpha=alpha_price,
    color="skyblue",
    edgecolors="black"
)

for i, txt in enumerate(grouped["분야"]):
    axes[0].annotate(txt, (grouped["등락률"][i], grouped["현재가"][i]))

axes[0].set_title("평균 주가 버블차트ㅋ")
axes[0].set_xlabel("평균 등락률")
axes[0].set_ylabel("평균 현재가")
axes[0].grid(True)


## 평균 등락률 기반 버블 차트
bubble_size_return = np.abs(grouped["등락률"]) * 150  # 약간 축소
alpha_return = normalize_alpha(np.abs(grouped["등락률"]))

axes[1].scatter(
    grouped["등락률"],
    grouped["현재가"],
    s=bubble_size_return,
    alpha=alpha_return,
    color="orange",
    edgecolors="black"
)

for i, txt in enumerate(grouped["분야"]):
    axes[1].annotate(txt, (grouped["등락률"][i], grouped["현재가"][i]))

axes[1].set_title("평균 등락률 버블차트")
axes[1].set_xlabel("평균 등락률")
axes[1].set_ylabel("평균 현재가")
axes[1].grid(True)


plt.tight_layout()
plt.show()